- name: Download the latest Wordpress package
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Unzip and unarchive the installation package
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Change owner of /var/www to apache
  file:
    path: /var/www
    state: directory
    recurse: yes
    owner: apache

- name: Copy wp-config.php file
  copy:
    src: ../files/wp-config.php
    dest: /var/www/html/
